variables:
  IMAGE_NAME: gcloud-k8

image: docker:latest

services:
  - docker:dind

before_script:
#  - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
 - docker login registry.gitlab.com
build-image-dev:
  stage: build
  script:
    - docker build -t registry.gitlab.com/a-pitters/gcloud-k8  .
    - docker push registry.gitlab.com/a-pitters/gcloud-k8
  only:
    - tags

build-image-tags:
  stage: build
  script:
    - docker build -t registry.gitlab.com/a-pitters/gcloud-k8:$CI_COMMIT_TAG  .
    - docker push registry.gitlab.com/a-pitters/gcloud-k8:$CI_COMMIT_TAG
  only:
    - tags
