variables:
  IMAGE_VERSION: $CI_COMMIT_TAG
  IMAGE_NAME: gcloud-k8

image: docker:latest

services:
  - docker:dind

before_script:
  - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin

build-image:
  stage: build
  script:
   - docker build -t $DOCKER_USER/$IMAGE_NAME:$IMAGE_VERSION .
   - docker push $DOCKER_USER/$IMAGE_NAME:$IMAGE_VERSION
  only:
    - tags