variables:
  IMAGE_NAME: gcloud-k8

image: docker:latest

services:
  - docker:dind

before_script:
 - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

build-image-master:
  stage: build
  script:
    - docker build -t registry.gitlab.com/a-pitters/gcloud-k8  .
    - docker push registry.gitlab.com/a-pitters/gcloud-k8
  only:
  - master

build-image-tags:
  stage: build
  script:
    - docker build -t registry.gitlab.com/a-pitters/gcloud-k8:$CI_COMMIT_TAG  .
    - docker push registry.gitlab.com/a-pitters/gcloud-k8:$CI_COMMIT_TAG
  only:
    - tags
